services:
  mongo:
    image: mongo:7
    container_name: gen-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    container_name: gen-backend
    build: ./backend
    ports:
      - "8800:8800"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: always

  admin:
    container_name: gen-admin
    build: ./admin
    ports:
      - "4000:4000"
    environment:
      - VITE_API_URL=http://backend:8800
    depends_on:
      - backend

  frontend:
    container_name: gen-frontend
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8800
    depends_on:
      - backend

volumes:
  mongo_data:
